### ISSUE TITLE
FileNotFoundError exception in Windows 

### ISSUE THREAD

**Issue by sfowlr** [varunagrawal/nuke#2]
System:
Windows 10 Pro, Build 10586.753
Python 2.7.10

Traceback:
```
C:\Users\Spencer\Documents\devel\myproject>pip install nuke
Collecting nuke
  Using cached nuke-1.0.5-py2.py3-none-any.whl
Collecting clint (from nuke)
Collecting args (from clint->nuke)
Installing collected packages: args, clint, nuke
Successfully installed args-0.1.0 clint-0.5.1 nuke-1.0.5

C:\Users\Spencer\Documents\devel\myproject>nuke
Are you sure you want to nuke directory C:\Users\Spencer\Documents\devel\myproject? [Y/n]
Nuking C:\Users\Spencer\Documents\devel\myproject
Traceback (most recent call last):
  File "D:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Python27\Scripts\nuke.exe\__main__.py", line 9, in <module>
  File "D:\Python27\lib\site-packages\nuke\nuke.py", line 47, in main
    nuke(directory)
  File "D:\Python27\lib\site-packages\nuke\nuke.py", line 25, in nuke
    except (FileNotFoundError,):
NameError: global name 'FileNotFoundError' is not defined
```

**Comment by varunagrawal** [comment]
I didn't realize `FileNotFoundError` doesn't exist in Python 2.7. Will need to add a test case for it. Thanks for reporting @sfowlr. I'll have a fix out in about 20 mins.

**Comment by varunagrawal** [comment]
The fix has been pushed and should be available in a couple of minutes. Please raise a new issue if it still exists.
